### PR TITLE
MDL-61722-33 policy: Set status to draft for inactive policies

### PR DESCRIPTION
**Pull request by sarjona**
This patch adds the "Set status to "Draft"" to all the inactive versions, instead of adding this menu option only when there is no other active or draft version. I think this makes the UX more consistent.

### CODE REVIEW

**Comment by mudrd8mz** [comment]
Thanks Sara for working on this. I think the patch must be extended a bit and it does not fit that easily on its own. The problem is with archived versions that have some associated acceptances. By re-activating an archive with acceptances, you end up with a draft that has some associated agreements. That is something the code does not expect - we display "N/A" there and we easily allow deleting of such version.

One way to sort this out might be to create a new copy of the archive (including a copy of embeded files), created with a draft status. The other option is to admit that drafts can have associated acceptances and fix the exisitng code to just expect that. Not sure which way is better now.

I'm sorry I did not realize this aspect earlier.

**Comment by sarjona** [comment]
After chat with Sander and David, we've decided implement the "re-activate as a new copy/version" option to avoid have drafts with acceptances.

**Comment by sarjona** [comment]
I've reviewed the code to create a new draft policy instead of changing only the archived flag ;-)
So it's ready again for PR!

**Review by mudrd8mz — APPROVED** [review]
Looks good, thanks Sara!

**Pull request merged**
