### PR TITLE
remove privacyofficer setting

### PR DESCRIPTION
**Pull request by marinaglancy**

### CODE REVIEW

**Review by mihailges — COMMENTED** [review]
Thanks Marina, it looks good to me. Before merging this, could you please rebase the latest MOODLE_34_STABLE.

**Comment by marinaglancy** [comment]
Thanks Mihail, I rebased. Were there merging conflicts?

**Comment by mihailges** [comment]
Thanks Marina. Just to avoid possible merge conflicts after the merge of the last PR.

**Review by mihailges — APPROVED** [review]
Thanks Marina.

**Pull request merged**
